# apiVersion: argoproj.io/v1alpha1
# kind: AppProject
# metadata:
#   name: default
# spec:
#   sourceRepos:
#     - '*'
#   destinations:
#     - namespace: '*'
#       name: '*'
#       server: '*'

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      name: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    # - group: "*"
    #   kind: "*"
